[package]
name = "neum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.1"
logos = "0.12.1"
notify = "5.1.0"
regex = "1.7.3"
